import {sameAnimal,canUpdateAnimal} from '../lib/animal-sync.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {webcrypto} from 'node:crypto';
import {validateAnimal} from '../lib/validate.mjs';import {configured,issueToken,authorized,matchPassword} from '../lib/auth.mjs';
const sample={id:'a1234567-1234-4234-8234-123456789012',chip:'000123456789012',name:'',color:'Preto e branco',block:'Bloco 2',photo:'data:image/jpeg;base64,YQ==',created:'2026-10-06T12:00:00.000Z',syncedTo:''};
test('chip identifier, optional name, mandatory fields and photo limits',()=>{assert.equal(validateAnimal(sample).chip,'000123456789012');assert.throws(()=>validateAnimal({...sample,chip:123}));assert.throws(()=>validateAnimal({...sample,block:''}));assert.throws(()=>validateAnimal({...sample,photo:'data:text/html;base64,YQ=='}));assert.throws(()=>validateAnimal({...sample,photo:'x'.repeat(1200001)}))});
test('authentication rejects wrong password and tampered token',()=>{process.env.APP_PASSWORD='uma-senha-forte-para-teste';process.env.SESSION_SECRET='a'.repeat(64);assert.ok(configured());assert.ok(matchPassword(process.env.APP_PASSWORD));assert.equal(matchPassword('errada'),false);const token=issueToken();const req=t=>new Request('https://example.test/api/animals',{headers:{authorization:'Bearer '+t}});assert.ok(authorized(req(token)));assert.equal(authorized(req(token+'tamper')),false);assert.equal(authorized(req('')),false)});
function client(seed=[],behavior={}){const saved=new Map(seed.map(r=>[r.chip,structuredClone(r)]));const elements=new Map();function el(id){if(!elements.has(id))elements.set(id,{id,textContent:'',innerHTML:'',value:'',hidden:false,style:{},className:'',classList:{toggle(){}},addEventListener(){},showModal(){},close(){}});return elements.get(id)}const bridge={readAll:()=>JSON.stringify({records:[...saved.values()]}),saveRecord:(s,replace)=>{const r=JSON.parse(s);if(behavior.failPut&&replace)return JSON.stringify({error:'Disk full'});if(!replace&&saved.has(r.chip))return JSON.stringify({error:'Duplicate'});saved.set(r.chip,r);return '{"ok":true}'},getConnection:()=>JSON.stringify({url:'https://server.test',token:'token'}),setConnection:()=>'{"ok":true}'};let postCount=0;const ctx={window:{NativeStore:bridge,addEventListener(){}},document:{getElementById:el},crypto:webcrypto,location:{pathname:'/',hash:'',protocol:'https:',origin:'https://appassets.androidplatform.net',hostname:'appassets.androidplatform.net'},history:{replaceState(){}},navigator:{onLine:true},setInterval(){},setTimeout,TextEncoder,Uint8Array,DataView,URL,AbortSignal,Blob,console,alert(){},confirm(){return behavior.confirm!==false},fetch:async(url,options)=>{if(behavior.offline)throw Error('Offline');if(options.method==='POST'){postCount++;if(behavior.conflict)return {ok:false,status:409,json:async()=>({error:'Chip duplicado'})};const r=JSON.parse(options.body);if(behavior.emulateServer)behavior.cloud=[{...r,revision:(r.serverRevision||0)+1}];return {ok:true,json:async()=>({id:r.id,status:'synced',revision:(r.serverRevision||0)+1})}}return {ok:true,json:async()=>({animals:behavior.cloud||[],next:0,more:false})}}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),ctx);return {ctx,saved,elements,run:s=>vm.runInContext(s,ctx),posts:()=>postCount}}
async function settle(){await new Promise(r=>setTimeout(r,10))}
test('offline records and photos remain local without false synchronization',async()=>{const c=client([sample],{offline:true});await settle();assert.equal(c.saved.get(sample.chip).syncedTo,'');assert.equal(c.saved.get(sample.chip).photo,sample.photo);assert.match(c.elements.get('syncStatus').textContent,/pendente/)});
test('successful synchronization only marks confirmed records',async()=>{const c=client([sample]);await settle();assert.equal(c.saved.get(sample.chip).syncedTo,'https://server.test');assert.equal(c.posts(),1);await c.run('syncNow()');assert.equal(c.posts(),1)});
test('duplicate chip from server preserves local record',async()=>{const c=client([sample],{conflict:true});await settle();assert.equal(c.saved.get(sample.chip).syncedTo,'');assert.equal(c.saved.get(sample.chip).photo,sample.photo)});
test('failed local confirmation is safely retried',async()=>{const behavior={failPut:true};const c=client([sample],behavior);await settle();assert.equal(c.saved.get(sample.chip).syncedTo,'');behavior.failPut=false;await c.run('syncNow()');assert.equal(c.posts(),2);assert.equal(c.saved.get(sample.chip).syncedTo,'https://server.test')});
test('new device recovers online records including photos',async()=>{const c=client([],{cloud:[sample]});await settle();assert.equal(c.saved.get(sample.chip).photo,sample.photo);assert.equal(c.saved.get(sample.chip).syncedTo,'https://server.test')});
test('Excel exporter is a ZIP workbook and uses typed text identifiers',()=>{const ctx={TextEncoder,Uint8Array,DataView,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(new URL('../public/excel.js',import.meta.url),'utf8'),ctx);const photo='data:image/jpeg;base64,'+fs.readFileSync(new URL('./fixtures/photo.jpg',import.meta.url)).toString('base64');const bytes=ctx.makeAnimalWorkbook([{...sample,photo},{...sample,chip:'000456',photo:''}],()=>true);assert.equal(new DataView(bytes.buffer).getUint32(0,true),0x04034b50);if(process.env.TEST_XLSX_PATH)fs.writeFileSync(process.env.TEST_XLSX_PATH,bytes)});
test('sex accepts male/female, rejects invalid choice and supports legacy',()=>{assert.equal(validateAnimal({...sample,sex:'Macho'}).sex,'Macho');assert.equal(validateAnimal({...sample,sex:'Fêmea'}).sex,'Fêmea');assert.equal(validateAnimal(sample).sex,'');assert.throws(()=>validateAnimal({...sample,sex:'Outro'}))});
test('wizard requires sex and saves the selected choice',async()=>{const c=client([],{offline:true});await settle();c.run("step=3;draft={chip:'000999',name:'',color:'Branco',sex:'',block:'A',kennel:'',photo:''};render()");await c.run('next()');assert.equal(c.run('step'),3);assert.match(c.elements.get('err').textContent,/Selecione macho/);c.run("draft.sex='Fêmea'");await c.run('next()');assert.equal(c.run('step'),4);await c.run('next()');assert.equal(c.run('step'),5);await c.run('next()');assert.equal(c.run('step'),5);assert.match(c.elements.get('err').textContent,/canil/);c.run("draft.kennel='2'");await c.run('next()');assert.equal(c.run('step'),6);await c.run('next()');assert.equal(c.run('step'),7);await c.run('next()');assert.equal(c.saved.get('000999').kennel,'2');assert.equal(c.saved.get('000999').block,'A');assert.equal(c.saved.get('000999').sex,'Fêmea');c.run('newAnimal()');assert.equal(c.run('draft.sex'),'')});

test('kennel supports legacy records and validates new values',()=>{assert.equal(validateAnimal(sample).kennel,'');assert.equal(validateAnimal({...sample,kennel:'2'}).kennel,'2');assert.throws(()=>validateAnimal({...sample,kennel:2}));assert.throws(()=>validateAnimal({...sample,kennel:'x'.repeat(121)}))});
test('report filters distinguish the same kennel in different blocks',async()=>{const c=client([{...sample,chip:'1',block:'A',kennel:'2'},{...sample,chip:'2',block:'B',kennel:'2'},{...sample,chip:'3',block:'A',kennel:'3'}],{offline:true});await settle();c.elements.get('filterBlock').value='A';c.elements.get('filterKennel').value='2';assert.equal(c.run('filteredRecords().length'),1);assert.equal(c.run('filteredRecords()[0].chip'),'1');c.elements.get('filterBlock').value='';assert.equal(c.run('filteredRecords().length'),2)});


test('cancelled deletion keeps the animal and photo',async()=>{const c=client([sample],{offline:true,confirm:false});await settle();await c.run('deleteAnimal(0)');assert.equal(c.run('records.length'),1);assert.equal(c.saved.get(sample.chip).deleted,undefined)});
test('offline deletion remains hidden and survives stale server data',async()=>{const behavior={offline:true,cloud:[{...sample,revision:1}],conflict:true};const c=client([{...sample,syncedTo:'https://server.test',serverRevision:1}],behavior);await settle();await c.run('deleteAnimal(0)');assert.equal(c.run('records.length'),0);assert.equal(c.saved.get(sample.chip).deleted,true);assert.equal(c.saved.get(sample.chip).syncedTo,'');behavior.offline=false;await c.run('syncNow()');assert.equal(c.saved.get(sample.chip).deleted,true);assert.equal(c.run('records.length'),0)});
test('confirmed deletion synchronizes and stays absent from reports',async()=>{const c=client([{...sample,syncedTo:'https://server.test',serverRevision:1}],{emulateServer:true});await settle();await c.run('deleteAnimal(0)');await settle();assert.equal(c.saved.get(sample.chip).serverRevision,2);assert.equal(c.saved.get(sample.chip).syncedTo,'https://server.test');assert.equal(c.run('filteredRecords().length'),0)});
test('remote deletion removes a previously synchronized animal',async()=>{const c=client([{...sample,syncedTo:'https://server.test',serverRevision:1}],{cloud:[{...sample,deleted:true,revision:2}]});await settle();assert.equal(c.run('records.length'),0);assert.equal(c.saved.get(sample.chip).deleted,true)});
test('editing preserves identity, date and photo and queues the changed location',async()=>{const c=client([{...sample,sex:'Macho',kennel:'2',syncedTo:'https://server.test',serverRevision:1}],{offline:true});await settle();c.run("editAnimal(0);draft.name='Rex';draft.block='B';draft.kennel='3';step=7");await c.run('next()');const r=c.saved.get(sample.chip);assert.equal(r.id,sample.id);assert.equal(r.created,sample.created);assert.equal(r.photo,sample.photo);assert.equal(r.name,'Rex');assert.equal(r.block,'B');assert.equal(r.kennel,'3');assert.equal(r.serverRevision,1);assert.equal(r.syncedTo,'')});
test('stale cloud copy cannot overwrite a pending edit on conflict',async()=>{const c=client([{...sample,name:'Local correction',serverRevision:1}],{cloud:[{...sample,revision:2}],conflict:true});await settle();assert.equal(c.saved.get(sample.chip).name,'Local correction');assert.equal(c.saved.get(sample.chip).syncedTo,'')});
test('re-registering an excluded chip reuses its identity for an explicit restore',async()=>{const c=client([{...sample,deleted:true,serverRevision:2,syncedTo:'https://server.test'}],{offline:true});await settle();c.run("draft={chip:'000123456789012',name:'Rex',color:'Preto',sex:'Macho',block:'A',kennel:'2',photo:''};step=7");await c.run('next()');assert.equal(c.saved.size,1);assert.equal(c.saved.get(sample.chip).id,sample.id);assert.equal(c.saved.get(sample.chip).deleted,false);assert.equal(c.saved.get(sample.chip).serverRevision,2)});

test('server update decisions reject stale revisions and recognize retry confirmations',()=>{const saved={...validateAnimal(sample),revision:2,deleted:true};const r={...validateAnimal(sample),deleted:true,serverRevision:1};assert.ok(sameAnimal(saved,r));assert.equal(canUpdateAnimal(saved,r),false);assert.ok(canUpdateAnimal(saved,{...r,serverRevision:2}));assert.equal(sameAnimal(saved,{...r,deleted:false}),false)});
